// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fiftyonedegrees.proxies;

public class Browser
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject browserMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FiftyOneDegrees.Browser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsMobile("IsMobile"),
		ScreenPixelsHeight("ScreenPixelsHeight"),
		ScreenPixelsWidth("ScreenPixelsWidth"),
		PlatformName("PlatformName"),
		PlatformVersion("PlatformVersion"),
		BrowserName("BrowserName"),
		BrowserVersion("BrowserVersion");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Browser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FiftyOneDegrees.Browser"));
	}

	protected Browser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject browserMendixObject)
	{
		if (browserMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("FiftyOneDegrees.Browser", browserMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FiftyOneDegrees.Browser");

		this.browserMendixObject = browserMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Browser.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static fiftyonedegrees.proxies.Browser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return fiftyonedegrees.proxies.Browser.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static fiftyonedegrees.proxies.Browser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fiftyonedegrees.proxies.Browser(context, mendixObject);
	}

	public static fiftyonedegrees.proxies.Browser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fiftyonedegrees.proxies.Browser.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of IsMobile
	 */
	public final java.lang.Boolean getIsMobile()
	{
		return getIsMobile(getContext());
	}

	/**
	 * @param context
	 * @return value of IsMobile
	 */
	public final java.lang.Boolean getIsMobile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsMobile.toString());
	}

	/**
	 * Set value of IsMobile
	 * @param ismobile
	 */
	public final void setIsMobile(java.lang.Boolean ismobile)
	{
		setIsMobile(getContext(), ismobile);
	}

	/**
	 * Set value of IsMobile
	 * @param context
	 * @param ismobile
	 */
	public final void setIsMobile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ismobile)
	{
		getMendixObject().setValue(context, MemberNames.IsMobile.toString(), ismobile);
	}

	/**
	 * @return value of ScreenPixelsHeight
	 */
	public final java.lang.Integer getScreenPixelsHeight()
	{
		return getScreenPixelsHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of ScreenPixelsHeight
	 */
	public final java.lang.Integer getScreenPixelsHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ScreenPixelsHeight.toString());
	}

	/**
	 * Set value of ScreenPixelsHeight
	 * @param screenpixelsheight
	 */
	public final void setScreenPixelsHeight(java.lang.Integer screenpixelsheight)
	{
		setScreenPixelsHeight(getContext(), screenpixelsheight);
	}

	/**
	 * Set value of ScreenPixelsHeight
	 * @param context
	 * @param screenpixelsheight
	 */
	public final void setScreenPixelsHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer screenpixelsheight)
	{
		getMendixObject().setValue(context, MemberNames.ScreenPixelsHeight.toString(), screenpixelsheight);
	}

	/**
	 * @return value of ScreenPixelsWidth
	 */
	public final java.lang.Integer getScreenPixelsWidth()
	{
		return getScreenPixelsWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of ScreenPixelsWidth
	 */
	public final java.lang.Integer getScreenPixelsWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ScreenPixelsWidth.toString());
	}

	/**
	 * Set value of ScreenPixelsWidth
	 * @param screenpixelswidth
	 */
	public final void setScreenPixelsWidth(java.lang.Integer screenpixelswidth)
	{
		setScreenPixelsWidth(getContext(), screenpixelswidth);
	}

	/**
	 * Set value of ScreenPixelsWidth
	 * @param context
	 * @param screenpixelswidth
	 */
	public final void setScreenPixelsWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer screenpixelswidth)
	{
		getMendixObject().setValue(context, MemberNames.ScreenPixelsWidth.toString(), screenpixelswidth);
	}

	/**
	 * @return value of PlatformName
	 */
	public final java.lang.String getPlatformName()
	{
		return getPlatformName(getContext());
	}

	/**
	 * @param context
	 * @return value of PlatformName
	 */
	public final java.lang.String getPlatformName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlatformName.toString());
	}

	/**
	 * Set value of PlatformName
	 * @param platformname
	 */
	public final void setPlatformName(java.lang.String platformname)
	{
		setPlatformName(getContext(), platformname);
	}

	/**
	 * Set value of PlatformName
	 * @param context
	 * @param platformname
	 */
	public final void setPlatformName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String platformname)
	{
		getMendixObject().setValue(context, MemberNames.PlatformName.toString(), platformname);
	}

	/**
	 * @return value of PlatformVersion
	 */
	public final java.lang.String getPlatformVersion()
	{
		return getPlatformVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of PlatformVersion
	 */
	public final java.lang.String getPlatformVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlatformVersion.toString());
	}

	/**
	 * Set value of PlatformVersion
	 * @param platformversion
	 */
	public final void setPlatformVersion(java.lang.String platformversion)
	{
		setPlatformVersion(getContext(), platformversion);
	}

	/**
	 * Set value of PlatformVersion
	 * @param context
	 * @param platformversion
	 */
	public final void setPlatformVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String platformversion)
	{
		getMendixObject().setValue(context, MemberNames.PlatformVersion.toString(), platformversion);
	}

	/**
	 * @return value of BrowserName
	 */
	public final java.lang.String getBrowserName()
	{
		return getBrowserName(getContext());
	}

	/**
	 * @param context
	 * @return value of BrowserName
	 */
	public final java.lang.String getBrowserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BrowserName.toString());
	}

	/**
	 * Set value of BrowserName
	 * @param browsername
	 */
	public final void setBrowserName(java.lang.String browsername)
	{
		setBrowserName(getContext(), browsername);
	}

	/**
	 * Set value of BrowserName
	 * @param context
	 * @param browsername
	 */
	public final void setBrowserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String browsername)
	{
		getMendixObject().setValue(context, MemberNames.BrowserName.toString(), browsername);
	}

	/**
	 * @return value of BrowserVersion
	 */
	public final java.lang.String getBrowserVersion()
	{
		return getBrowserVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of BrowserVersion
	 */
	public final java.lang.String getBrowserVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BrowserVersion.toString());
	}

	/**
	 * Set value of BrowserVersion
	 * @param browserversion
	 */
	public final void setBrowserVersion(java.lang.String browserversion)
	{
		setBrowserVersion(getContext(), browserversion);
	}

	/**
	 * Set value of BrowserVersion
	 * @param context
	 * @param browserversion
	 */
	public final void setBrowserVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String browserversion)
	{
		getMendixObject().setValue(context, MemberNames.BrowserVersion.toString(), browserversion);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return browserMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fiftyonedegrees.proxies.Browser that = (fiftyonedegrees.proxies.Browser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FiftyOneDegrees.Browser";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
